### ISSUE TITLE
Auto taskpane open feature not working on MAC 

### ISSUE THREAD

**Issue by PriyaKatkade** [OfficeDev/Office-OOXML-EmbedAddin#4]
Hello,
I want to open taskpane automatically after opening a document. I followed https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document this link.
According to link, I have configured WebExtension in document OOXML like below

            TaskPane taskPane = new TaskPane();
            document.WebExtensionTaskPanes.Add(taskPane);
            taskPane.DockState = TaskPaneDockState.Right;
            taskPane.IsVisible = true;
            taskPane.Width = 300;
            taskPane.WebExtension.Id = "09c70a19-bd78-4fc4-a183-30d856b6e48c";
            taskPane.WebExtension.Reference.Id = "09c70a19-bd78-4fc4-a183-30d856b6e48c";
            taskPane.WebExtension.Reference.Version = "1.0.0.0";
            taskPane.WebExtension.Reference.StoreType = "ExCatalog";
            taskPane.WebExtension.Reference.Store = "EXCatalog";
            
            taskPane.WebExtension.Properties.Add(new WebExtensionProperty("Office.AutoShowTaskpaneWithDocument", "true"));

I have deployed my addin on [Centralized Deployment](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment) using Micrsoft 365 admin center .

Auto taskpane open feature works perfect on Windows. When we open document on Windows taskpane with ID 09c70a19-bd78-4fc4-a183-30d856b6e48c open automatically. But when we open the same document on MAC, it opens the empty taskpane. Its not loading the provided application in taskpane. Also not showing any error.

Will anybody please help me to find the cause?

**Comment by AbidRahman-MSFT** [comment]
Hey Priya, 

Thanks for reporting the issue. This scenario should be working on Mac and this behavior is a bug.

Are you able to provide more information regarding this issue, such as:
1. Are there any failed network requests when the empty taskpane is opened in Mac? Is it opening your add-in but is unable to load the content? Can you provide a screenshot of what the 'empty' taskpane looks like?
2. Can you provide screenshots or a sample add-in that we can use to try and recreate the same scenario?
3. Does this only occurs when using Centralized Deployment, can you repeat the same scenario for Office Store?
4. What is the version for the MAC Office? For auto open taskpane, it is required to be Build 15.34.17051500+. Can you verify this is correct?

Thanks,
Abid

**Comment by PriyaKatkade** [comment]
Hello @AbidRahman-MSFT,

Thanks for the help.
I gone through add-in again on MAC. I came to know that MAC has cached the old add-in where TaskpaneID was not set to "Office.AutoShowTaskpaneWithDocument". That's why the taskpane was not loading the contents. I cleared all the cache data and now its working as expected.
