### ISSUE TITLE
Use Open XML to Auto Open and Excel Task Pane Add-in

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/Office-OOXML-EmbedAddin#5]
Hi @Rick-Kirkham 

We are seeking to Auto Open an Task Pane Add-in required in an Excel Workbook for users who do not have the Task Pane Add-in installed. The Add-in is published in AppSource.

We understand from [Use Open XML to tag the document](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document#use-open-xml-to-tag-the-document) that to do this, `webextension` and `taskpane` parts have to be added to the workbook to set `visibility=1` and add other references.

Ideally, we would like to add/set these parts when the Add-in is used so that when the Workbook is saved and sent to another "Add-in not installed user", they would be prompted to Trust the Add-in, it will be installed, enabled for the workbook and (we assume) added to their My Add-ins list.

Some hurdles we have discovered/expect:

1. There is no equivalent [OoxmlCoercion](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/office-add-in-requirement-sets?view=common-js-preview&irgwc=1&OCID=AID2200057_aff_7815_1243925&tduid=(ir__vldi9j3htokf6numxvgw0cx1fe2xvzvakanikzm900)(7815)(1243925)(je6NUbpObpQ-1NhT.kkKrquj7YwXAsY7QA)()&irclickid=_vldi9j3htokf6numxvgw0cx1fe2xvzvakanikzm900#ooxmlcoercion) method for Excel (Word only)?
2. You cannot write these two `parts` to an open Workbook Open XML with the approach of the C# code in this repo?
3. How can we implement a solution using JavaScript and/or the Excel JS API

Can you please comment on the above, and provide any advice for our use case and requirements.

Thanks for your help.
David

cc @sanjeet-pm

**Comment by Rick-Kirkham** [comment]
1. Correct. It is not available for Excel.
2. I don't understand this question. It doesn't look grammatical. You _can_ use C# code, as shown in this repo, to add the parts to a document. 
3. The article that you linked to shows how to do this.

**Comment by david-ps** [comment]
@Rick-Kirkham Thanks for the feedback. 
Sorry I was not clear in Q2, here's my question...

Can the  `webextension` and `taskpane `parts be created/updated when the Workbook is open in Excel by JavaScript in an Excel TaskPane Add-in?

**Comment by Rick-Kirkham** [comment]
@david-ps The **Tag the document on the client side** section of the article that you linked to tells you how to write these parts to the open workbook in an add-in, using JavaScript. But visibility will be set to 0. I don't think there's any way to set visibility to 1 using JavaScript. 

If the question is, could you set visibility to 1 using C# while the workbook is open in Excel, I suspect that you can't; but you'll need to test to be sure. I don't know of anyone who's tried it. 

You could have a button in the task pane that invokes a web API and passes the URL of the workbook. That API opens the workbook, adds the markup, and saves it. But I suspect that it would error at that point because the workbook is open somewhere else. 

Sorry, to be uncertain, but I'm afraid this is a case where they only way to get the answer is to try it and see.

**Comment by Rick-Kirkham** [comment]
I'll close this for now, but you can still add comments to it and we'll see them.

**Comment by david-ps** [comment]
@Rick-Kirkham We have not been able to add/modify `webextension` and `taskpane` parts with JavaScript and cannot access or make changes to them while the file is open in Excel. 

So it appears the only way to use Open Office XML markup to trigger the AutoOpen feature is outside the session. 

There are no events or way we have found to initiate this automatically on close, via say a Web API. 

This is a frustrating and **critical problem** when seeking to distribute Excel files dependent on Add-ins to new users.

Perhaps a solution would be for the [TaskpaneID](https://docs.microsoft.com/en-us/javascript/api/manifest/action?view=common-js-preview#taskpaneid) and [Office.AutoShowTaskpaneWithDocument](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document#step-1-specify-the-task-pane-to-open) scope to be extended in the API. 

Where do you suggest is the best place submit the request?

**Comment by Rick-Kirkham** [comment]
Make this suggestion at the Microsoft 365 Developer Platform Tech Community Ideas forum: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by david-ps** [comment]
@Rick-Kirkham  Ok, I have added ideas there before that do not even receive any type of acknowledgement but will do so again. Thanks. 

[Suggestion added to Tech Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/sharing-excel-workbooks-dependent-on-add-ins-can-cause/idi-p/3453198#M1008)

FYI: Latest Microsoft 365 Developer Platform Tech Community Ideas forum Stats:
New = 638 (Even items submitted Apr 15 2021 are still "New" - no comments or status change by Microsoft)
Working on It = 3 (including 2 items that have 0 Upvotes, even though 57 Items => 10 Upvotes)
Completed = 2
OMG

cc @davidchesnut

**Comment by david-ps** [comment]
@Rick-Kirkham did I describe the situation in my [Tech Idea Forum Post](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/sharing-excel-workbooks-dependent-on-add-ins-can-cause/idi-p/3453198#M1008) accurately? 

If it is correct then perhaps I should post this as an issue in [Office JS](https://github.com/OfficeDev/office-js/issues)?

Thanks for your help.

**Comment by Rick-Kirkham** [comment]
I think you have described it well. 
It can't hurt to raise an issue on the Office-js repo. 
I will report your statistics internally and see if this is expected or not.

**Comment by davidchesnut** [comment]
Hi @david-ps, just want to check if you looked into a new feature with shared runtime that lets you start your add-in automatically the next time the workbook is opened. [Run code in your Office Add-in when the document opens](https://docs.microsoft.com/office/dev/add-ins/develop/run-code-on-document-open). One of the things you can do when your add-in starts (on doc open) is show the task pane. [Show or hide the task pane of your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/develop/show-hide-add-in). Basically you would just call the code to show your task pane from the onReady() handler. You can also do background activities on doc load (before you show the task pane) which can be helpful in some scenarios. There's a sample [here you can try out](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-shared-runtime-scenario) and it's interesting to examine the OOXML generated (very similar to the first doc you referenced.)

Hope this helps,
David

**Comment by david-ps** [comment]
Hi @davidchesnut, Thanks for the information. Yes, I have seen these docs but I do not believe they do address the use case I have outlined and now posted as a critical issue in Office JS.
